name: Build GDExtension
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:
  workflow_call:

env:
  LIBNAME: godot-ndi

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup clang-format
        shell: bash
        run: |
          python -m pip install clang-format

      - name: Run clang-format
        shell: bash
        run: |
          clang-format src/** --dry-run --Werror

  build:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { platform: linux, arch: x86_64, os: ubuntu-latest },
            { platform: windows, arch: x86_64, os: windows-latest },
            { platform: macos, arch: universal, os: macos-latest },
          ]
        target-type: [template_debug, template_release]
        float-precision: [single, double]

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build GDExtension
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.target.platform }}
          arch: ${{ matrix.target.arch }}
          float-precision: ${{ matrix.float-precision }}
          target-type: ${{ matrix.target-type }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item addons/${{ env.LIBNAME }}/bin/windows/* -Include *.exp,*.lib,*.pdb -Force

      - name: Copy license files
        run: |
          cp LICENSE addons/${{ env.LIBNAME }}/LICENSE
          cp README.md addons/${{ env.LIBNAME }}/README.md
          cp NOTICE.md addons/${{ env.LIBNAME }}/NOTICE.md

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIBNAME }}-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ./*/${{ env.LIBNAME }}
            !./addons/${{ env.LIBNAME }}/project.godot

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ env.LIBNAME }}
          pattern: ${{ env.LIBNAME }}-*
          delete-merged: true

  release:
    runs-on: ubuntu-latest
    needs: merge
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LIBNAME }}
          path: ${{ env.LIBNAME }}

      - name: Zip Artifact Back Up
        run: |
          sudo apt-get install -y zip
          cd ${{ env.LIBNAME }}
          zip -r ../${{ env.LIBNAME }}.zip .

      - name: Create Release Draft
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: ${{ env.LIBNAME }}.zip
          draft: true
          generate_release_notes: true
